<?php
use Drupal\Component\Utility\Html;

/**
 * Preprocess variables for html templates.
 * @param $variables
 */
 
function hook_preprocess_html(&$variables) {
  // Add node title as body class.
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $node = $node->getTranslation('en');
    $title = $node->label();
    $title = str_replace(' ', '-', $title);
    $title = str_replace('_', '-', $title);
    $variables['title_en'] = strtolower($title);
  }
  }
